### ISSUE TITLE
Bilder des GUI-Layouts hinzufügen

### ISSUE THREAD

**Issue by cateye0434** [cateyeRgr/bike-shop-scheduler#4]
Bitte noch Bilder einfügen @cateyeRgr

**Comment by cateyeRgr** [comment]
Close #4 Screenshots hier:
![TerminAnlegenGUI](https://user-images.githubusercontent.com/74964267/108601350-6e722980-739c-11eb-8f5f-54f3cc918042.PNG)
![TerminSuchenGUI](https://user-images.githubusercontent.com/74964267/108601353-70d48380-739c-11eb-967e-58c6efc4e039.PNG)
![KundeAnlegenGUI](https://user-images.githubusercontent.com/74964267/108601342-674b1b80-739c-11eb-96ed-060be8f78c3d.PNG)
![MitarbeiterAnlegenGUI](https://user-images.githubusercontent.com/74964267/108601345-6a460c00-739c-11eb-8406-2851ca3a3ef4.PNG)
